"""Export ros_gz_bridge parameter YAML."""
from __future__ import annotations

from pathlib import Path

import yaml

from domain.models import SensorModel
from exporter.gz_fortress_topics import ROS_MSG_TYPES, gz_topic_for_sensor


def export_bridge_yaml(model: SensorModel, output_path: Path) -> Path:
    entries: list[dict] = []
    for sensor in model.sensors:
        if not sensor.enabled:
            continue
        ros_type, gz_type = ROS_MSG_TYPES[sensor.kind]
        entries.append(
            {
                "ros_topic_name": sensor.rosTopic,
                "gz_topic_name": gz_topic_for_sensor(model.gzModelName, sensor),
                "ros_type_name": ros_type,
                "gz_type_name": gz_type,
                "direction": "GZ_TO_ROS",
                "sensor_id": sensor.id,
                "sensor_name": sensor.name,
                "sensor_kind": sensor.kind.value,
                "parent_link": sensor.parentLink,
            }
        )

    doc = {
        "bridge": entries,
        "config": {
            "topic_prefix": model.topicPrefix,
            "gz_model_name": model.gzModelName,
            "note": (
                "gz_topic_name uses /world/default/ — adjust world name after first sim spawn if needed."
            ),
        },
    }
    header = "# Auto-generated by QuadRL Sensor Editor\n"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(header + yaml.dump(doc, default_flow_style=False, sort_keys=False))
    return output_path
