"""Export RL observation contract YAML."""
from __future__ import annotations

from pathlib import Path

import yaml

from domain.models import SensorInstance, SensorKind, SensorModel
from exporter.gz_fortress_topics import ROS_MSG_TYPES


def _observation_key(sensor: SensorInstance) -> str:
    return sensor.name.replace("-", "_").replace(" ", "_")


def _fields_for(sensor: SensorInstance) -> list[str]:
    if sensor.kind == SensorKind.IMU:
        fields = ["angular_velocity", "linear_acceleration"]
        if sensor.imu and sensor.imu.enableOrientation:
            fields.append("orientation")
        return fields
    if sensor.kind == SensorKind.CONTACT:
        return ["contacts"]
    return ["ranges", "angle_min", "angle_max"]


def export_observations_yaml(
    model: SensorModel,
    output_path: Path,
    controllers_rel: str,
    gains_rel: str,
) -> Path:
    observations: dict = {}
    for sensor in model.sensors:
        if not sensor.enabled:
            continue
        ros_type, _ = ROS_MSG_TYPES[sensor.kind]
        observations[_observation_key(sensor)] = {
            "kind": sensor.kind.value,
            "topic": sensor.rosTopic,
            "msg_type": ros_type.replace("/msg/", "/"),
            "rate_hz": sensor.updateRate,
            "parent_link": sensor.parentLink,
            "fields": _fields_for(sensor),
        }

    doc = {
        "robot_name": model.robotName,
        "sim_urdf": f"sens_{model.projectName}_rl.urdf",
        "sim_sdf": f"sens_{model.projectName}.sdf",
        "topic_prefix": model.topicPrefix,
        "gz_model_name": model.gzModelName,
        "control": {
            "controllers_yaml": controllers_rel,
            "gains_yaml": gains_rel,
        },
        "observations": observations,
    }
    header = "# Auto-generated by QuadRL Sensor Editor — load in your ROS2 RL env node\n"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(header + yaml.dump(doc, default_flow_style=False, sort_keys=False))
    return output_path
