"""Export unified RL training config for SB3 + ROS2/Gazebo."""
from __future__ import annotations

from pathlib import Path

import yaml

from domain.models import CurriculumConfig, CurriculumStage, RlTrainerModel
from planner.curriculum import curriculum_total_timesteps
from storage import project_storage


def _termination_export(t) -> dict:
    return {
        "max_episode_steps": t.maxEpisodeSteps,
        "fall_base_height_threshold": t.fallBaseHeightThreshold,
        "max_tilt_rad": t.maxTiltRad,
        "max_joint_torque": t.maxJointTorque,
        "timeout_truncation": t.timeoutTruncation,
    }


def _advance_criteria_export(c) -> dict:
    return {
        "min_mean_episode_reward": c.minMeanEpisodeReward,
        "min_episode_length_frac": c.minEpisodeLengthFrac,
        "max_fall_rate": c.maxFallRate,
        "min_timesteps_in_stage": c.minTimestepsInStage,
    }


def _stage_export(stage: CurriculumStage) -> dict:
    return {
        "id": stage.id,
        "name": stage.name,
        "order": stage.order,
        "description": stage.description,
        "timesteps": stage.timesteps,
        "command": {
            "target_lin_vel_x": stage.targetLinVelX,
            "target_ang_vel_z": stage.targetAngVelZ,
        },
        "reward_terms": [_reward_term_export(t) for t in stage.rewardTerms],
        "termination": _termination_export(stage.termination),
        "advance_criteria": _advance_criteria_export(stage.advanceCriteria),
    }


def _curriculum_export(cur: CurriculumConfig) -> dict:
    stages = sorted(cur.stages, key=lambda s: s.order)
    return {
        "enabled": cur.enabled,
        "curriculum_id": cur.curriculumId,
        "name": cur.name,
        "description": cur.description,
        "current_stage_index": cur.currentStageIndex,
        "load_previous_checkpoint": cur.loadPreviousCheckpoint,
        "reset_policy_on_stage_advance": cur.resetPolicyOnStageAdvance,
        "total_timesteps": curriculum_total_timesteps(cur),
        "stages": [_stage_export(s) for s in stages],
    }


def _reward_term_export(term) -> dict:
    return {
        "id": term.id,
        "type": term.type,
        "category": term.category,
        "weight": term.weight,
        "enabled": term.enabled,
        "params": dict(term.params),
    }


def export_rl_yaml(model: RlTrainerModel, project_name: str) -> Path:
    out = project_storage.export_rl_yaml_path(project_name)
    out.parent.mkdir(parents=True, exist_ok=True)

    t = model.termination

    body = {
        "algorithm": "PPO",
        "framework": "stable_baselines3",
        "project": project_name,
        "robot": model.robotName,
        "ppo_config_file": f"ppo_{project_name}_config.yaml",
        "env": {
            "observations_file": f"sens_{project_name}_observations.yaml",
            "gains_file": f"ctrl_{project_name}_gains.yaml",
            "sim_urdf": f"sens_{project_name}_rl.urdf",
        },
        "task": {
            "preset_id": model.selectedPresetId,
            "reward_terms": [_reward_term_export(term) for term in model.rewardTerms],
            "termination": _termination_export(t),
        },
        "curriculum": _curriculum_export(model.curriculum),
        "logging": {
            "tensorboard_root": "runs",
            "tensorboard_note": (
                "Training writes runs/<timestamp>/run_info.yaml; curriculum stages log to "
                "runs/<timestamp>/<order>_<stage_id>_<name>/ (SB3 PPO_* subdirs inside)."
            ),
        },
        "custom_params": dict(model.customParams),
        "machine_profile": model.machineProfile.model_dump() if model.machineProfile else None,
        "recommendation_notes": model.recommendationNotes,
    }

    header = (
        f"# Auto-generated by QuadRL RL Trainer Editor\n"
        f"# Project: {project_name}\n"
        f"# PPO hyperparameters and parallel envs: export from PPO Planner ({body['ppo_config_file']})\n"
    )
    out.write_text(header + yaml.dump(body, default_flow_style=False, sort_keys=False))
    return out
