"""Default pose helpers for geometry editor and export."""
from __future__ import annotations

from typing import Optional

import yaml

from domain.models import Joint, JointType, Pose, RobotModel


DEFAULT_POSE_NAME = "Default Stand"


def suggest_stand_joint_value(joint: Joint) -> float:
    """Heuristic stand pose from joint naming and limits."""
    if joint.type in (JointType.FIXED,):
        return 0.0
    name = joint.name.lower()
    if any(tok in name for tok in ("thigh", "hfe", "upper_leg", "femur")):
        return min(joint.upperLimit, max(joint.lowerLimit, 0.75))
    if any(tok in name for tok in ("calf", "knee", "kfe", "shank", "lower_leg", "tibia")):
        return max(joint.lowerLimit, min(joint.upperLimit, -1.35))
    if any(tok in name for tok in ("hip", "abad", "abaduction")):
        return 0.0
    if joint.type == JointType.PRISMATIC:
        return 0.0
    mid = (joint.lowerLimit + joint.upperLimit) / 2.0
    return float(mid * 0.25)


def get_default_pose(model: RobotModel) -> Optional[Pose]:
    if model.defaultPoseId:
        pose = next((p for p in model.poses if p.id == model.defaultPoseId), None)
        if pose:
            return pose
    return model.poses[0] if model.poses else None


def ensure_default_pose(model: RobotModel, *, init_stand: bool = False) -> RobotModel:
    """Ensure model has a default pose; optionally seed stand joint angles."""
    movable = [j for j in model.joints if j.type != JointType.FIXED]
    if init_stand and movable:
        for joint in movable:
            joint.defaultValue = suggest_stand_joint_value(joint)

    if not model.poses:
        values = {j.id: j.defaultValue for j in movable}
        pose = Pose(name=DEFAULT_POSE_NAME, jointValues=values)
        model.poses.append(pose)
        model.defaultPoseId = pose.id
        return model

    pose = get_default_pose(model)
    if pose and not model.defaultPoseId:
        model.defaultPoseId = pose.id

    if pose and init_stand:
        for joint in movable:
            if joint.id not in pose.jointValues:
                pose.jointValues[joint.id] = joint.defaultValue
            else:
                joint.defaultValue = pose.jointValues[joint.id]
    elif pose:
        for joint in movable:
            if joint.id in pose.jointValues:
                joint.defaultValue = pose.jointValues[joint.id]
    return model


def sync_pose_from_joints(model: RobotModel, pose_id: str) -> Optional[Pose]:
    pose = next((p for p in model.poses if p.id == pose_id), None)
    if not pose:
        return None
    pose.jointValues = {
        j.id: j.defaultValue for j in model.joints if j.type != JointType.FIXED
    }
    return pose


def apply_pose_to_joints(model: RobotModel, pose_id: str) -> Optional[Pose]:
    pose = next((p for p in model.poses if p.id == pose_id), None)
    if not pose:
        return None
    for joint in model.joints:
        if joint.id in pose.jointValues:
            joint.defaultValue = pose.jointValues[joint.id]
    return pose


def reset_pose_to_stand(model: RobotModel, pose_id: str) -> Optional[Pose]:
    for joint in model.joints:
        if joint.type != JointType.FIXED:
            joint.defaultValue = suggest_stand_joint_value(joint)
    return sync_pose_from_joints(model, pose_id)


def export_default_pose_yaml(model: RobotModel) -> dict:
    pose = get_default_pose(model)
    joint_map: dict[str, float] = {}
    id_to_name = {j.id: j.name for j in model.joints}
    if pose:
        for jid, val in pose.jointValues.items():
            name = id_to_name.get(jid)
            if name:
                joint_map[name] = float(val)
    else:
        for j in model.joints:
            if j.type != JointType.FIXED:
                joint_map[j.name] = float(j.defaultValue)

    spawn_z = float(model.metadata.get("standSpawnZ", model.metadata.get("stand_base_z", 0.5)))
    return {
        "name": pose.name if pose else DEFAULT_POSE_NAME,
        "spawn": {"x": 0.0, "y": 0.0, "z": spawn_z, "roll": 0.0, "pitch": 0.0, "yaw": 0.0},
        "joints": joint_map,
    }


def write_default_pose_export(model: RobotModel, output_path) -> None:
    body = export_default_pose_yaml(model)
    header = "# Auto-generated by QuadRL Geometry Editor — default spawn / reset pose\n"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(header + yaml.dump(body, default_flow_style=False, sort_keys=False), encoding="utf-8")
