"""Export PPO config for QuadRL training scripts."""
from __future__ import annotations

import json
from pathlib import Path

import yaml

from domain.models import ExportConfigFormat, PpoPlannerModel
from exporter.format_registry import FORMAT_EXTENSIONS, JSON_LIKE, config_filename
from exporter.toml_util import dump_toml
from storage import project_storage


def _resolved_device(model: PpoPlannerModel) -> str:
    dev = model.params.device.value
    if dev != "auto":
        return dev
    if model.machineProfile and model.machineProfile.gpuAvailable:
        return "cuda"
    return "cpu"


def _checkpoint_export(model: PpoPlannerModel) -> dict:
    c = model.checkpoint
    return {
        "enabled": c.enabled,
        "directory": c.directory,
        "frequency": c.frequency.value,
        "frequency_steps": c.frequencySteps,
        "keep_last_n": c.keepLastN,
        "filename_template": c.filenameTemplate,
        "save_on_interrupt": c.saveOnInterrupt,
    }


def _best_model_export(model: PpoPlannerModel) -> dict:
    b = model.bestModel
    return {
        "enabled": b.enabled,
        "metric": b.metric.value,
        "mode": b.mode.value,
        "directory": b.directory,
        "filename": b.filename,
        "min_improvement": b.minImprovement,
    }


def build_ppo_config_body(model: PpoPlannerModel, project_name: str) -> dict:
    p = model.params
    par = model.parallel
    body: dict = {
        "algorithm": "PPO",
        "framework": "stable_baselines3",
        "project": project_name,
        "robot": model.robotName,
        "device": _resolved_device(model),
        "hyperparameters": {
            "learning_rate": p.learningRate,
            "n_steps": p.nSteps,
            "batch_size": p.batchSize,
            "n_epochs": p.nEpochs,
            "gamma": p.gamma,
            "gae_lambda": p.gaeLambda,
            "clip_range": p.clipRange,
            "ent_coef": p.entCoef,
            "vf_coef": p.vfCoef,
            "max_grad_norm": p.maxGradNorm,
            "total_timesteps": p.totalTimesteps,
        },
        "parallel": {
            "num_envs": par.numEnvs,
            "vec_env_type": par.vecEnvType.value,
            "n_proc": par.nProc,
        },
        "checkpoint": _checkpoint_export(model),
        "best_model": _best_model_export(model),
    }
    opts = model.exportFormat
    if opts.includeMachineProfile and model.machineProfile:
        body["machine_profile"] = model.machineProfile.model_dump()
    if opts.includeRecommendationNotes and model.recommendationNotes:
        body["recommendation_notes"] = model.recommendationNotes
    return body


def export_ppo_config_path(
    project_name: str,
    fmt: ExportConfigFormat,
) -> Path:
    return project_storage.project_dir(project_name) / project_storage.EXPORTS_DIR / config_filename(
        project_name, fmt
    )


def _header_for_format(fmt: ExportConfigFormat, project_name: str, *, enabled: bool) -> str:
    if not enabled:
        return ""
    if fmt == ExportConfigFormat.YAML:
        return f"# Auto-generated by QuadRL PPO Planner\n# Project: {project_name}\n"
    if fmt == ExportConfigFormat.TOML:
        return f"# Auto-generated by QuadRL PPO Planner\n# Project: {project_name}\n"
    if fmt in JSON_LIKE:
        return f"// Auto-generated by QuadRL PPO Planner\n// Project: {project_name}\n"
    return ""


def _sort_dict(data: dict) -> dict:
    return {k: _sort_dict(v) if isinstance(v, dict) else v for k, v in sorted(data.items())}


def serialize_ppo_config(body: dict, fmt: ExportConfigFormat, project_name: str, opts) -> str:
    payload = _sort_dict(body) if opts.sortKeys else body
    header = _header_for_format(fmt, project_name, enabled=opts.includeHeaderComments)

    if fmt == ExportConfigFormat.JSON:
        return header + json.dumps(payload, indent=2, sort_keys=opts.sortKeys)
    if fmt == ExportConfigFormat.JSON_MIN:
        return header + json.dumps(payload, separators=(",", ":"), sort_keys=opts.sortKeys)
    if fmt == ExportConfigFormat.TOML:
        return header + dump_toml(payload)
    return header + yaml.dump(payload, default_flow_style=False, sort_keys=opts.sortKeys)


def export_ppo_config(
    model: PpoPlannerModel,
    project_name: str,
    fmt: ExportConfigFormat,
) -> Path:
    out = export_ppo_config_path(project_name, fmt)
    out.parent.mkdir(parents=True, exist_ok=True)
    body = build_ppo_config_body(model, project_name)
    out.write_text(serialize_ppo_config(body, fmt, project_name, model.exportFormat))
    return out


def export_ppo_configs(model: PpoPlannerModel, project_name: str) -> list[Path]:
    """Write one file per selected export format."""
    formats = model.exportFormat.formats or [ExportConfigFormat.YAML]
    return [export_ppo_config(model, project_name, fmt) for fmt in formats]


def export_ppo_yaml(model: PpoPlannerModel, project_name: str) -> Path:
    """Backward-compatible single-file export (first selected format)."""
    paths = export_ppo_configs(model, project_name)
    return paths[0]
