"""Export PPO config for QuadRL training scripts."""
from __future__ import annotations

from pathlib import Path

import yaml

from domain.models import PpoPlannerModel
from storage import project_storage


def _resolved_device(model: PpoPlannerModel) -> str:
    dev = model.params.device.value
    if dev != "auto":
        return dev
    if model.machineProfile and model.machineProfile.gpuAvailable:
        return "cuda"
    return "cpu"


def export_ppo_yaml(model: PpoPlannerModel, project_name: str) -> Path:
    out = project_storage.export_ppo_yaml_path(project_name)
    out.parent.mkdir(parents=True, exist_ok=True)

    p = model.params
    body = {
        "algorithm": "PPO",
        "project": project_name,
        "robot": model.robotName,
        "device": _resolved_device(model),
        "hyperparameters": {
            "learning_rate": p.learningRate,
            "n_steps": p.nSteps,
            "batch_size": p.batchSize,
            "n_epochs": p.nEpochs,
            "gamma": p.gamma,
            "gae_lambda": p.gaeLambda,
            "clip_range": p.clipRange,
            "ent_coef": p.entCoef,
            "vf_coef": p.vfCoef,
            "max_grad_norm": p.maxGradNorm,
            "total_timesteps": p.totalTimesteps,
            "num_envs": p.numEnvs,
        },
        "machine_profile": model.machineProfile.model_dump() if model.machineProfile else None,
        "recommendation_notes": model.recommendationNotes,
    }

    header = (
        f"# Auto-generated by QuadRL PPO Planner\n"
        f"# Project: {project_name}\n"
    )
    out.write_text(header + yaml.dump(body, default_flow_style=False, sort_keys=False))
    return out
