"""Export ros2_control URDF and controller YAML for ProfileA."""
from __future__ import annotations

import xml.etree.ElementTree as ET
from pathlib import Path

import yaml

from domain.models import ControlModel, JointControlConfig


def _indent(elem: ET.Element, level: int = 0) -> None:
    pad = "\n" + "  " * level
    if len(elem):
        if not elem.text or not elem.text.strip():
            elem.text = pad + "  "
        for child in elem:
            _indent(child, level + 1)
        child.tail = pad
    if level and (not elem.tail or not elem.tail.strip()):
        elem.tail = pad


def _build_ros2_control_block(model: ControlModel, joints: list[JointControlConfig]) -> ET.Element:
    rc = ET.Element("ros2_control", name="GazeboSim", type="system")
    hardware = ET.SubElement(rc, "hardware")
    plugin = ET.SubElement(hardware, "plugin")
    plugin.text = model.hardwarePlugin

    for j in joints:
        jel = ET.SubElement(rc, "joint", name=j.name)
        cmd = ET.SubElement(jel, "command_interface", name=j.commandInterface)
        if j.type != "continuous":
            pmin = ET.SubElement(cmd, "param", name="min")
            pmin.text = str(j.lowerLimit)
            pmax = ET.SubElement(cmd, "param", name="max")
            pmax.text = str(j.upperLimit)
        pkp = ET.SubElement(cmd, "param", name="kp")
        pkp.text = str(j.kp)
        pkd = ET.SubElement(cmd, "param", name="kd")
        pkd.text = str(j.kd)
        for iface in j.stateInterfaces:
            ET.SubElement(jel, "state_interface", name=iface)

    return rc


def export_controllers_yaml(model: ControlModel, output_path: Path) -> Path:
    joints = [j.name for j in model.actuatedJoints if j.enabled]

    flat: dict = {
        "controller_manager": {
            "ros__parameters": {
                "update_rate": model.updateRate,
                "joint_state_broadcaster": {
                    "type": "joint_state_broadcaster/JointStateBroadcaster",
                },
                "position_controller": {
                    "type": (
                        "joint_trajectory_controller/JointTrajectoryController"
                        if model.controllerType == "joint_trajectory_controller"
                        else "forward_command_controller/ForwardCommandController"
                    ),
                },
            }
        },
        "joint_state_broadcaster": {"ros__parameters": {}},
        "position_controller": {
            "ros__parameters": {
                "joints": joints,
                **(
                    {"interface_name": "position"}
                    if model.controllerType != "joint_trajectory_controller"
                    else {}
                ),
            }
        },
        "/**": {
            "ros__parameters": {
                "control_profile": model.trainingProfile.value,
                "robot_name": model.robotName,
            }
        },
    }

    joint_lines = "\n".join(f"      - {n}" for n in joints)
    header = (
        f"# Auto-generated by QuadRL Control Editor\n"
        f"# Profile: {model.trainingProfile.value}\n"
        f"# Joints ({len(joints)}):\n"
        f"{joint_lines}\n"
    )
    output_path.write_text(header + yaml.dump(flat, default_flow_style=False, sort_keys=False))
    return output_path


def export_gains_yaml(model: ControlModel, output_path: Path) -> Path:
    gains = {
        "profile": model.trainingProfile.value,
        "joints": {
            j.name: {
                "kp": j.kp,
                "kd": j.kd,
                "default_position": j.defaultPosition,
                "action_scale": j.actionScale,
                "effort_limit": j.effort,
                "velocity_limit": j.velocity,
            }
            for j in model.actuatedJoints
            if j.enabled
        },
    }
    output_path.write_text(yaml.dump(gains, default_flow_style=False, sort_keys=False))
    return output_path


def export_all(
    model: ControlModel,
    phy_urdf_path: Path,
    urdf_out: Path,
    controllers_out: Path,
    gains_out: Path,
) -> dict[str, str]:
    joints = [j for j in model.actuatedJoints if j.enabled]
    tree = ET.parse(phy_urdf_path)
    root = tree.getroot()

    for el in list(root.findall("ros2_control")):
        root.remove(el)

    root.append(_build_ros2_control_block(model, joints))

    gz_plugin_name = f"{model.simPlugin}_system"
    controllers_rel = controllers_out.name
    for gz in list(root.findall("gazebo")):
        plug = gz.find("plugin")
        if plug is not None and "ros2_control" in (plug.get("filename") or ""):
            root.remove(gz)

    gz = ET.SubElement(root, "gazebo")
    plugin_el = ET.SubElement(
        gz,
        "plugin",
        filename=f"{model.simPlugin}/{gz_plugin_name}",
        name="gz_ros2_control",
    )
    params = ET.SubElement(plugin_el, "parameters")
    params.text = controllers_rel

    _indent(root)
    tree.write(urdf_out, encoding="unicode", xml_declaration=True)

    export_controllers_yaml(model, controllers_out)
    export_gains_yaml(model, gains_out)

    return {
        "urdf": str(urdf_out),
        "controllers": str(controllers_out),
        "gains": str(gains_out),
    }
