"""Export ros2_control URDF and controller YAML for ProfileA."""
from __future__ import annotations

import xml.etree.ElementTree as ET
from pathlib import Path

import yaml

from domain.models import (
    DEFAULT_SIM_CONTROLLER,
    SIM_CONTROLLER_JOINT_TRAJECTORY,
    ControlModel,
    JointControlConfig,
    apply_fortress_gazebo_defaults,
)


def _indent(elem: ET.Element, level: int = 0) -> None:
    pad = "\n" + "  " * level
    if len(elem):
        if not elem.text or not elem.text.strip():
            elem.text = pad + "  "
        for child in elem:
            _indent(child, level + 1)
        child.tail = pad
    if level and (not elem.tail or not elem.tail.strip()):
        elem.tail = pad


def _build_ros2_control_block(model: ControlModel, joints: list[JointControlConfig]) -> ET.Element:
    rc = ET.Element("ros2_control", name="GazeboSim", type="system")
    hardware = ET.SubElement(rc, "hardware")
    plugin = ET.SubElement(hardware, "plugin")
    plugin.text = model.hardwarePlugin

    for j in joints:
        jel = ET.SubElement(rc, "joint", name=j.name)
        cmd = ET.SubElement(jel, "command_interface", name=j.commandInterface)
        if j.type != "continuous":
            pmin = ET.SubElement(cmd, "param", name="min")
            pmin.text = str(j.lowerLimit)
            pmax = ET.SubElement(cmd, "param", name="max")
            pmax.text = str(j.upperLimit)
        pkp = ET.SubElement(cmd, "param", name="kp")
        pkp.text = str(j.kp)
        pkd = ET.SubElement(cmd, "param", name="kd")
        pkd.text = str(j.kd)
        for iface in j.stateInterfaces:
            ET.SubElement(jel, "state_interface", name=iface)

    return rc


def _controller_plugin_type(controller_type: str) -> str:
    if controller_type == SIM_CONTROLLER_JOINT_TRAJECTORY:
        return "joint_trajectory_controller/JointTrajectoryController"
    return "forward_command_controller/ForwardCommandController"


def _controller_instance_name(controller_type: str) -> str:
    if controller_type == SIM_CONTROLLER_JOINT_TRAJECTORY:
        return "joint_trajectory_controller"
    return "position_controller"


def _controller_ros_parameters(model: ControlModel, joints: list[str]) -> dict:
    if model.controllerType == SIM_CONTROLLER_JOINT_TRAJECTORY:
        return {
            "joints": joints,
            "command_interfaces": ["position"],
            "state_interfaces": ["position", "velocity"],
        }
    return {
        "joints": joints,
        "interface_name": "position",
    }


def export_controllers_yaml(model: ControlModel, output_path: Path) -> Path:
    joints = [j.name for j in model.actuatedJoints if j.enabled]
    ctrl_name = _controller_instance_name(model.controllerType)

    flat: dict = {
        "controller_manager": {
            "ros__parameters": {
                "update_rate": model.updateRate,
                "joint_state_broadcaster": {
                    "type": "joint_state_broadcaster/JointStateBroadcaster",
                },
                ctrl_name: {
                    "type": _controller_plugin_type(model.controllerType),
                },
            }
        },
        "joint_state_broadcaster": {"ros__parameters": {}},
        ctrl_name: {
            "ros__parameters": _controller_ros_parameters(model, joints),
        },
        "/**": {
            "ros__parameters": {
                "control_profile": model.trainingProfile.value,
                "robot_name": model.robotName,
            }
        },
    }

    joint_lines = "\n".join(f"      - {n}" for n in joints)
    header = (
        f"# Auto-generated by QuadRL Control Editor\n"
        f"# Profile: {model.trainingProfile.value}\n"
        f"# Controller: {model.controllerType}\n"
        f"# Joints ({len(joints)}):\n"
        f"{joint_lines}\n"
    )
    output_path.write_text(header + yaml.dump(flat, default_flow_style=False, sort_keys=False))
    return output_path


def export_gains_yaml(model: ControlModel, output_path: Path) -> Path:
    gains = {
        "profile": model.trainingProfile.value,
        "controller_type": model.controllerType,
        "joints": {
            j.name: {
                "kp": j.kp,
                "kd": j.kd,
                "default_position": j.defaultPosition,
                "action_scale": j.actionScale,
                "effort_limit": j.effort,
                "velocity_limit": j.velocity,
            }
            for j in model.actuatedJoints
            if j.enabled
        },
    }
    output_path.write_text(yaml.dump(gains, default_flow_style=False, sort_keys=False))
    return output_path


def export_all(
    model: ControlModel,
    phy_urdf_path: Path,
    urdf_out: Path,
    controllers_out: Path,
    gains_out: Path,
) -> dict[str, str]:
    # ProfileA simulation always exports joint_trajectory_controller + Fortress plugin.
    if model.trainingProfile.value == "ProfileA":
        model.controllerType = DEFAULT_SIM_CONTROLLER
        apply_fortress_gazebo_defaults(model)

    joints = [j for j in model.actuatedJoints if j.enabled]
    tree = ET.parse(phy_urdf_path)
    root = tree.getroot()

    for el in list(root.findall("ros2_control")):
        root.remove(el)

    root.append(_build_ros2_control_block(model, joints))

    controllers_rel = controllers_out.name
    for gz in list(root.findall("gazebo")):
        plug = gz.find("plugin")
        fn = plug.get("filename") if plug is not None else ""
        plug_name = plug.get("name") if plug is not None else ""
        if plug is not None and (
            "ros2_control" in fn or "ros2_control" in plug_name
        ):
            root.remove(gz)

    gz = ET.SubElement(root, "gazebo")
    plugin_el = ET.SubElement(
        gz,
        "plugin",
        filename=model.simPluginFilename,
        name=model.simPluginClass,
    )
    params = ET.SubElement(plugin_el, "parameters")
    params.text = controllers_rel

    _indent(root)
    tree.write(urdf_out, encoding="unicode", xml_declaration=True)

    export_controllers_yaml(model, controllers_out)
    export_gains_yaml(model, gains_out)

    return {
        "urdf": str(urdf_out),
        "controllers": str(controllers_out),
        "gains": str(gains_out),
    }
